version: '3.1'


services:

  db:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: bookmedik
      MARIADB_USER: bookmedik
      MARIADB_PASSWORD: bookmedik
    volumes:
      - db:/var/lib/mysql


  bookmedik:
    container_name: bookmedik
    image: crespillo/bookmedik:v1
    restart: always
    environment:
      USER: bookmedik
      PASSWD: bookmedik
      HOST: db
      DATABASE: bookmedik      
    ports:
      - 8080:80
    depends_on:
      - db



volumes:
    db:
